name: beer
version: 0.0.1
author: Marlon Silva Carvalho (marlon.carvalho@gmail.com)
description: API for exposing beer data.
homepage: https://github.com/marloncarvalho/darter-beer-api
environment:
  sdk: '>=1.8.3 <2.0.0'
dependencies:
  collection: '>=1.1.1 <2.0.0'
  darter: '>=0.0.1-beta <0.0.5'
  appengine: '>=0.2.1 <0.3.0'
#  darter:
#    path: /Users/marloncarvalho/git/darter/